BR-4 Test Case
Malankar/bookmarker pull request #9
Opened 2024-10-31 11:58 UTC by Malankar

This pull request introduces several changes to enhance the testing capabilities and improve the bookmark management functionality. The most important changes include adding testing scripts and dependencies, improving error handling and responses in the bookmark controller, and setting up unit tests for the bookmark controller.

### Testing Enhancements:

* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L7-R9): Added `test` and `coverage` scripts and included `vitest` and `@vitest/coverage-v8` as dev dependencies. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L7-R9) [[2]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R25-R29)
* [`vite.config.js`](diffhunk://#diff-58e6f63d87181b1c6a8cb6e5f1691df04aa32854456efcd52ca71c8541375d26R1-R34): Configured Vitest for unit testing with coverage reporting and specific include/exclude patterns.

### Bookmark Controller Improvements:

* [`src/controllers/bookmarkController.js`](diffhunk://#diff-1e7c6a266cf13cea39476d0b8cf37cd2b11703dab35ad0d5a1749dc521ee6a6bL15-L19): Improved error handling and response structure in the `getBookmarkById` and `createBookmark` functions. [[1]](diffhunk://#diff-1e7c6a266cf13cea39476d0b8cf37cd2b11703dab35ad0d5a1749dc521ee6a6bL15-L19) [[2]](diffhunk://#diff-1e7c6a266cf13cea39476d0b8cf37cd2b11703dab35ad0d5a1749dc521ee6a6bL30-R25)
* [`src/routes/bookmarkRoutes.js`](diffhunk://#diff-a3c2ebf95eb002d1e29c26cec22a8cb858de044b7565a027938a8707806b49e3R3-R5): Added `express.Router()` to set up routes for the bookmark controller.

### Unit Tests:

* [`test/controllers/bookmarkController.test.js`](diffhunk://#diff-788362b297cc977cf3088d2ce154513f062351d1096811241a9a246c7c899d2eR1-R114): Created unit tests for the bookmark controller using Vitest, covering various scenarios such as fetching all bookmarks, fetching a bookmark by ID, creating a bookmark, and deleting a bookmark.

2025-01-28 07:31 UTC, Bala-raj requested changes

2025-01-28 07:31 UTC, Bala-raj commented on test/routes/bookmarkRoutes.test.js
This test suite for rate limiting is a good start, but it has some significant flaws that make it unreliable and potentially misleading. Let's break down the issues and discuss improvements:

Problems:

- Timing Issues: The biggest problem is that these tests rely on actual time passing.  Your rate limiting is configured for 100 requests within 15 minutes.  Your tests are trying to send 100 requests immediately.  This is highly unlikely to reflect real-world behavior and might not even trigger the rate limiter correctly, especially if the requests are processed very quickly.  The tests are essentially just checking that 100 requests don't immediately cause a 429, which isn't a very meaningful test.

- Flaky Tests: Because of the timing issue, these tests are highly flaky.  They might pass sometimes and fail other times depending on how quickly your server processes the requests and how the rate limiter is implemented.  Flaky tests are a major problem because they erode confidence in your test suite.

- No Control over Time:  You have no way to control the passage of time within your tests.  You need a way to simulate the 15-minute window without actually waiting for 15 minutes.

- Limited Scenarios:  You're only testing the edge case of exactly 100 requests and then one more.  You should test other scenarios, such as:

    - What happens if you send 50 requests, wait for 5 minutes, and then send another 50?
    - What happens if you send 101 requests very quickly?
    - What is the behavior with different HTTP methods (GET, PUT, DELETE)? Rate limiting should ideally apply to all relevant methods.

2025-01-28 07:31 UTC, Bala-raj commented on test/services/bookmarkService.test.js
> +        id: "49fb6870-478f-4a6a-a839-e6e198adfb94",
Test Data Generation: Using hardcoded UUIDs in your tests.  This makes the tests less flexible and harder to read.  It's highly recommended to use a library like uuid to generate UUIDs within your tests.  This will make your tests more robust and less prone to errors.

2025-01-28 07:31 UTC, Bala-raj commented on test/services/bookmarkService.test.js
> +    it("should throw validation error if the id is not a valid GUID", async () => {
More Comprehensive Input Validation Tests: You have one general test for invalid input in createBookmark and getBookmarkById.  You should break this down into more specific tests for each validation rule.  For example:

- Test with empty title.
- Test with very long title.
- Test with invalid URLs (missing protocol, malformed domain, etc.).
- Test with special characters in the title (and decide how you want to handle them).

2025-01-28 07:31 UTC, Bala-raj commented on test/services/bookmarkService.test.js
> +      expect(result).toEqual(1);
Test deleteBookmarkById returning value: The test for deleteBookmarkById currently only checks that the returned value is 1. It would be better to check if the correct number of deleted rows is returned, in case you want to delete multiple bookmarks at once in the future.

2025-02-01 14:12 UTC, Malankar commented on test/controllers/bookmarkController.test.js
> +      const mockBookmarks = [{ id: 1, title: 'Test Bookmark', url: 'http://example.com' }];
It is done

2025-02-01 14:12 UTC, Malankar commented on test/controllers/bookmarkController.test.js
this is done as well thanks for recommendation

2025-02-01 14:13 UTC, Malankar commented on test/controllers/bookmarkController.test.js
> +      const res = {
I have abstract res for now as its seems to be same but not the req object

2025-02-01 14:13 UTC, Malankar commented on test/controllers/bookmarkController.test.js
> +    it('should return all bookmarks with status 200', async () => {
this is done as well

2025-02-03 15:15 UTC, Malankar commented on test/middleware/errorHandler.test.js
This is done

2025-02-03 15:20 UTC, Malankar commented on test/db/schema.test.js
We don't have it in drizzle but we are doing it in joi validation instead

2025-02-04 06:40 UTC, Malankar commented on test/services/bookmarkService.test.js
> +        id: "49fb6870-478f-4a6a-a839-e6e198adfb94",
This is done

2025-02-04 06:50 UTC, Malankar commented on test/services/bookmarkService.test.js
> +    it("should throw validation error if the id is not a valid GUID", async () => {
Hi @Bala-raj 
In getBookmarkById we only accept uuid of the bookmark so I had only one test. I have added more test cases for createBookmark please check

2025-02-04 06:51 UTC, Malankar commented on test/services/bookmarkService.test.js
> +      expect(result).toEqual(1);
Hi @Bala-raj 
deleteBookmarkById functionality is to delete one bookmark only for now there is no functionality to delete multiple for now because of that we will be returning array of one bookmark which is delete that's why it is one. let me know if you want me to implement delete multiple bookmark endpoint

2025-02-04 08:17 UTC, Malankar commented on test/routes/bookmarkRoutes.test.js
I have added detailed rate limiting test cases please check

2025-02-09 15:01 UTC, merged